name: update-ics
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
  push:

jobs:
  build:
    name: Update ics
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write
      packages: read
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: install pipx
        run: |
          sudo apt-get update
          sudo apt-get install pipx
          pipx ensurepath

      - name: install Poetry
        run: pipx install poetry==2.1.1

      - name: install dependencies
        run: poetry install

      - name: generate calendar files
        run: poetry run python run.py
        env:
          HOLODULE_YOUTUBE_KEY: ${{ secrets.HOLODULE_YOUTUBE_KEY }}

      - name: generate documentation
        run: poetry run make docs
        env:
          CI: yes # Skip updating gettext files, which somehow causes errors

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: public/

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
    permissions:
      pages: write
      id-token: write
