name: update-ics
on:
  schedule:
    - cron: '12/15 * * * *'
  workflow_dispatch:
  push:
    branches:
      - master
    tags-ignore:
      - "**"

jobs:
  update:
    name: Update ics
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.9 # CHECK .devcontainer/devcontainer.json!!!
      - uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-${{ hashFiles('requirements.txt') }}
      - name: install deps
        run: pip install -r requirements.txt
      - name: run holodule-ical
        run: python run.py
        env:
          HOLODULE_PAGE: ${{ secrets.HOLODULE_PAGE }}
          HOLODULE_YOUTUBE_KEY: ${{ secrets.HOLODULE_YOUTUBE_KEY }}
      - name: deploy to public branch
        uses: peaceiris/actions-gh-pages@v3.5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: public
          keep_files: true
          commit_message: update ics
          cname: sarisia.cc
          user_name: mntaqua
          user_email: '91774192+mntaqua@users.noreply.github.com'
      - name: post status to Discord
        if: failure()
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: holodule - update ics
